### ISSUE TITLE
TypeError: on_train_epoch_end() missing 1 required positional argument: 'outputs'

### ISSUE THREAD

**Issue by yx8njit** [scverse/scvi-tools#1641]
Could you post a workable requirements.txt? Since there are so many dependencies used by scvi-tools, it is hard to get all versions work together. I had been tuning the versions for a week but still was not able to run the train successfully. Thanks!

    model.train(max_epochs=100, check_val_every_n_epoch=100)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/scvi/model/base/_training_mixin.py", line 70, in train
    return runner()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/scvi/model/base/_trainrunner.py", line 75, in __call__
    self.trainer.fit(self.training_plan, train_dl, val_dl)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/scvi/lightning/_trainer.py", line 131, in fit
    super().fit(*args, **kwargs)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "/home/yx8/singlecell/venv-scvi/lib64/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
TypeError: on_train_epoch_end() missing 1 required positional argument: 'outputs'

```python
[CODE HERE]
```
    cm = np.array(count_matrix['X']).astype("float64")
    adata = sc.AnnData(cm, dtype="float64")
    scvi.data.setup_anndata(adata)
    model = scvi.model.SCVI(adata)
    model.train(max_epochs=100, check_val_every_n_epoch=100)

```pytb
[ERROR HERE]
```

#### Versions:

> VERSION
scvi==0.6.8
scvi-tools==0.9.0b1
pytorch-lightning==1.5.10
torch==1.10.2

**Comment by adamgayoso** [comment]
Can you please try with python >=3.7? It seems you’re using 3.6, which is grabbing the last available supported version of our software that works on 3.6, which is quite old. 

Using regular installation channels should work in this case.

**Comment by adamgayoso** [comment]
Closing due to inactivity.
